const ProductManager = require("./ProdManager.js");
let prodManager = new ProductManager();
console.log(prodManager);
console.log(prodManager.getProducts());
prodManager.addProduct("Blue Lock", "Tomo 11", 1200, "sin img", 20);
prodManager.addProduct("Jujutsu Kaisen", "Tomo 0", 1350, "sin img", 25);
prodManager.addProduct("Darling In The FranXx", "Tomo 4", 1000, "sin img", 40);
prodManager.addProduct("Bunny Girl Senpai", "Tomo 1", 1500, "sin img", 15);
prodManager.addProduct("Wotakoi", "Tomo 7", 1300, "sin img", 35);
prodManager.addProduct("Hanako Kun", "Tomo 15", 1300, "sin img", 10);
console.log(prodManager.getProducts());
//prodManager.getProductById(3);
//prodManager.deleteProduct(2);
//prodManager.updateProduct(1, {precio: 4000});
console.log(prodManager.getProducts());